### ISSUE TITLE
USER STORY: READ MESSAGES

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/cafe-lalba#13]
As a **Sit Admin** i can **read messages from guests** so that **i'm in touch in case of any issue**

**Comment by Kiko-Climent** [comment]
**acceptance criteria**

- [ ]  Messages are timestamped, displaying the date and time they were sent.
- [ ] The interface provides options to mark messages as read/unread
- [ ] Each message contains necessary details such as at least, email/contact, subject and message content.

**tasks**

- [ ]
