### ISSUE TITLE
USER STORY: BOOKING CONFIRMATION

### ISSUE THREAD

**Issue by Kiko-Climent** [Kiko-Climent/cafe-lalba#7]
As a **User** i can **get a Confirmation** so that **im sure that my request has been received**

**Acceptance Criteria**

- [x] Users receive an immediate confirmation message or email upon successful booking.
- [x] Include reservation details in the confirmation communication (date, time, number of guests).

**Tasks**

- [x] Implement a notification system to immediately confirm successful bookings.
- [ ] Design email templates or in-app messages for confirmation and reminders.
